// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytxqtofzoxgkyrahehii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0eHF0b2Z6b3hna3lyYWhlaGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTczMDgsImV4cCI6MjA1ODI3MzMwOH0.butNzupnP0BKkmX4fEhDzrknbCuczwtjdpcCfeDPnwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);